name             'centos7-develop'
maintainer       'c-styles'
maintainer_email 'eisuke@c-styles.jp'
license          'All rights reserved'
description      'Learning Material for CentOS7'
long_description ''
version          '0.1.0'
