name             'centos7-develop'
maintainer       'c-styles'
maintainer_email 'eisuke@c-styles.jp'
license          'All rights reserved'
description      'Learning Material for CentOS7'
long_description ''
version          '0.1.0'

supports 'centos'

depends 'selinux', '>= 0.9.0'
depends 'yum-ius', '>= 0.4.2'
depends 'yum-epel', '>= 0.6.3'
depends 'php', '>= 1.7.2'
depends 'httpd', '>= 0.2.19'
depends 'openssl', '>= 4.4.0'
